#!/usr/bin/env bash
# ---
# artifact_id: onboard-tenant-mantis
# artifact_type: orchestration_script
# version: 2.0.0-COMPREHENSIVE
# constraints_mapped: ["C1","C2","C3","C4","C5","C7","V1"]
# canonical_path: 05-CONFIGURATIONS/scripts/onboard-tenant.sh
# domain: 05-CONFIGURATIONS
# subdomain: scripts
# agent_role: configurations-master
# language_lock: es-ES
# validation_command: orchestrator-engine.sh --domain configurations --strict
# tier: 3
# immutable: true
# requires_human_approval_for_changes: true
# audience: ["agentic_assistants"]
# human_readable: false
# checksum_sha256: "89165a612057674830f628dce1b11603abaebf7c60bde89d2a372385200497bf"
# ---
set -euo pipefail

# [CONSTRAINT_MAP]
# C1: Usa templates base, nunca modifica estructura de skills existente
# C2: Todo artefacto generado queda en repositorio (traceable)
# C3: Cero hardcodeo de credenciales o paths sensibles
# C4: Registro atómico en canonical_registry.json + timestamp
# C5: Validación estricta de inputs, deps y JSON
# C7: Idempotente: ejecución múltiple segura sin duplicación
# V1: Genera política RLS SQL para aislamiento lógico de tenant

# [DEPENDENCIES]
# git, jq, sed, bash >= 4.3
# [INTERFACE_ALIGNMENT]
# Consumes: interface-spec.yaml (db_schema pattern), mapping.yaml (tenant vars)
# Produces: 02-SKILLS/<TENANT>/, RLS SQL script, registry entry

# [GLOBALS]
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$(dirname "$(dirname "$SCRIPT_DIR")")")"
readonly SKILLS_DIR="${REPO_ROOT}/02-SKILLS"
readonly REGISTRY_FILE="${REPO_ROOT}/canonical_registry.json"
readonly TEMPLATE_FILE="${SCRIPT_DIR}/../templates/skill-template.md"
readonly RLS_DIR="${REPO_ROOT}/05-CONFIGURATIONS/terraform/migrations/rls"

mkdir -p "$SKILLS_DIR" "$RLS_DIR"

# [LOGGING]
log() { printf '[%s] [%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1" "$2" | tee -a /dev/stderr; }
log_info()  { log "INFO"  "$1"; }
log_warn()  { log "WARN"  "$1"; }
log_error() { log "ERROR" "$1"; }

# [ARGS]
TENANT_ID="${1:-}"
TENANT_NAME="${2:-}"
FORCE="${3:-false}"

if [[ -z "$TENANT_ID" || -z "$TENANT_NAME" ]]; then
  log_error "USO: $0 <tenant_id> <tenant_name> [--force]"
  exit 1
fi

# [VALIDATION]
for cmd in git jq sed; do
  command -v "$cmd" >/dev/null 2>&1 || { log_error "DEPENDENCY_FAIL: $cmd requerido"; exit 1; }
done

# V1: Formato estricto de tenant_id (lowercase, alfanumérico + _, 3-32 chars)
if ! [[ "$TENANT_ID" =~ ^[a-z0-9_]{3,32}$ ]]; then
  log_error "VALIDATION_FAIL: tenant_id inválido. Use 3-32 chars [a-z0-9_]"
  exit 1
fi

TENANT_UPPER="$(echo "$TENANT_ID" | tr '[:lower:]' '[:upper:]')"
SKILLS_PATH="${SKILLS_DIR}/${TENANT_UPPER}"

if [[ -d "$SKILLS_PATH" && "$FORCE" != "true" ]]; then
  log_warn "TENANT_EXISTS: ${TENANT_ID} ya registrado. Use --force para sobrescribir"
  exit 1
fi

# [PHASE_1: SKILLS STRUCTURE (C1, C2)]
phase_skills() {
  log_info "PHASE_1_START: Creando estructura de skills para ${TENANT_ID}"
  
  mkdir -p "${SKILLS_PATH}/docs" "${SKILLS_PATH}/data"
  
  if [[ -f "$TEMPLATE_FILE" ]]; then
    cp "$TEMPLATE_FILE" "${SKILLS_PATH}/README.md"
    sed -i "s/{tenant_id}/$TENANT_ID/g; s/{tenant_name}/$TENANT_NAME/g; s/{date}/$(date -u +%Y-%m-%d)/g" "${SKILLS_PATH}/README.md"
  else
    log_warn "TEMPLATE_MISSING: ${TEMPLATE_FILE} no encontrado. Creando mínimo viable"
    cat > "${SKILLS_PATH}/README.md" <<EOF
# Skill: ${TENANT_NAME}
tenant_id: ${TENANT_ID}
created_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
  fi
  
  log_info "PHASE_1_COMPLETE: Skills directory ready"
}

# [PHASE_2: RLS POLICY GENERATION (V1)]
phase_rls_sql() {
  log_info "PHASE_2_START: Generando política RLS para aislamiento de tenant"
  
  local sql_file="${RLS_DIR}/rls-${TENANT_ID}.sql"
  
  # Idempotente: DROP IF EXISTS + CREATE
  cat > "$sql_file" <<EOF
-- RLS Policy for tenant: ${TENANT_ID}
-- Generated by: onboard-tenant.sh (MANTIS v2.0.0)
-- Constraint: V1 (tenant isolation)
-- Apply with: psql \${DATABASE_URL} -f ${sql_file}

BEGIN;
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
    RAISE NOTICE 'pgvector not loaded. Skipping vector-specific RLS.';
  ELSE
    EXECUTE 'CREATE EXTENSION IF NOT EXISTS vector';
  END IF;
END \$\$;

-- Enable RLS on target tables if not already enabled
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE embeddings ENABLE ROW LEVEL SECURITY;

-- Drop existing policy to ensure idempotency
DROP POLICY IF EXISTS tenant_${TENANT_ID}_isolation ON documents;
DROP POLICY IF EXISTS tenant_${TENANT_ID}_isolation ON embeddings;

-- Create tenant-scoped isolation policies
CREATE POLICY tenant_${TENANT_ID}_isolation ON documents
  FOR ALL
  USING (tenant_id = '${TENANT_ID}');

CREATE POLICY tenant_${TENANT_ID}_isolation ON embeddings
  FOR ALL
  USING (tenant_id = '${TENANT_ID}');

COMMIT;
EOF
  
  log_info "PHASE_2_COMPLETE: RLS script generated at ${sql_file}"
}

# [PHASE_3: REGISTRY UPDATE (C4, C5)]
phase_registry() {
  log_info "PHASE_3_START: Actualizando canonical_registry.json"
  
  if [[ ! -f "$REGISTRY_FILE" ]]; then
    log_error "REGISTRY_MISSING: ${REGISTRY_FILE} no existe"
    exit 1
  fi
  
  # Validate JSON integrity before modification
  jq empty "$REGISTRY_FILE" >/dev/null 2>&1 || { log_error "REGISTRY_CORRUPT: JSON inválido"; exit 1; }
  
  # Atomic update (tmp + mv)
  local tmp_reg="${REGISTRY_FILE}.tmp"
  jq --arg tid "$TENANT_ID" \
     --arg tname "$TENANT_NAME" \
     --arg tupper "$TENANT_UPPER" \
     --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
     '.tenants[$tid] = {
        name: $tname,
        tenant_upper: $tupper,
        onboarded_at: $ts,
        skills_path: ("02-SKILLS/" + $tupper + "/"),
        rls_script: ("05-CONFIGURATIONS/terraform/migrations/rls/rls-" + $tid + ".sql"),
        status: "active",
        constraint_v1_applied: true
      }' "$REGISTRY_FILE" > "$tmp_reg" && mv "$tmp_reg" "$REGISTRY_FILE"
  
  log_info "PHASE_3_COMPLETE: Registry updated atomically"
}

# [EXECUTION PIPELINE]
log_info "ONBOARD_START: ${TENANT_ID} (${TENANT_NAME})"
phase_skills
phase_rls_sql
phase_registry

log_info "ONBOARD_SUCCESS: ${TENANT_ID} listo para despliegue RLS y validación"


---
